//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<OrderItems> OrderItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ProductCategories> ProductCategories { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<View_Sales> View_Sales { get; set; }
        public virtual DbSet<View_SalesDetails> View_SalesDetails { get; set; }
    
        public virtual ObjectResult<GetOrderDetailsById_Result> GetOrderDetailsById(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderDetailsById_Result>("GetOrderDetailsById", orderIDParameter);
        }
    
        public virtual ObjectResult<GetProducts_Result> GetProducts(Nullable<bool> iS_ADMIN, Nullable<bool> aDMIN_AS_USER, Nullable<bool> qUERY_BY_KEYWORD, Nullable<bool> qUERY_BY_CATEGORY, string kEYWORDS, Nullable<int> cATEGORY_ID)
        {
            var iS_ADMINParameter = iS_ADMIN.HasValue ?
                new ObjectParameter("IS_ADMIN", iS_ADMIN) :
                new ObjectParameter("IS_ADMIN", typeof(bool));
    
            var aDMIN_AS_USERParameter = aDMIN_AS_USER.HasValue ?
                new ObjectParameter("ADMIN_AS_USER", aDMIN_AS_USER) :
                new ObjectParameter("ADMIN_AS_USER", typeof(bool));
    
            var qUERY_BY_KEYWORDParameter = qUERY_BY_KEYWORD.HasValue ?
                new ObjectParameter("QUERY_BY_KEYWORD", qUERY_BY_KEYWORD) :
                new ObjectParameter("QUERY_BY_KEYWORD", typeof(bool));
    
            var qUERY_BY_CATEGORYParameter = qUERY_BY_CATEGORY.HasValue ?
                new ObjectParameter("QUERY_BY_CATEGORY", qUERY_BY_CATEGORY) :
                new ObjectParameter("QUERY_BY_CATEGORY", typeof(bool));
    
            var kEYWORDSParameter = kEYWORDS != null ?
                new ObjectParameter("KEYWORDS", kEYWORDS) :
                new ObjectParameter("KEYWORDS", typeof(string));
    
            var cATEGORY_IDParameter = cATEGORY_ID.HasValue ?
                new ObjectParameter("CATEGORY_ID", cATEGORY_ID) :
                new ObjectParameter("CATEGORY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts", iS_ADMINParameter, aDMIN_AS_USERParameter, qUERY_BY_KEYWORDParameter, qUERY_BY_CATEGORYParameter, kEYWORDSParameter, cATEGORY_IDParameter);
        }
    }
}
